CREATE TABLE "auto_ship_chat" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "auto_ship_chat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"shop_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"status_chat" boolean DEFAULT true NOT NULL,
	"status_ship" boolean DEFAULT true NOT NULL,
	CONSTRAINT "auto_ship_chat_shop_id_unique" UNIQUE("shop_id")
);
--> statement-breakpoint
CREATE TABLE "booking_orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "booking_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"shop_id" bigint NOT NULL,
	"booking_sn" varchar NOT NULL,
	"order_sn" varchar,
	"region" varchar,
	"booking_status" varchar,
	"match_status" varchar,
	"shipping_carrier" text,
	"create_time" bigint,
	"update_time" bigint,
	"recipient_address" jsonb,
	"item_list" jsonb,
	"dropshipper" text,
	"dropshipper_phone" varchar,
	"cancel_by" varchar,
	"cancel_reason" varchar,
	"fulfillment_flag" varchar,
	"pickup_done_time" bigint,
	"tracking_number" text,
	"is_printed" boolean DEFAULT false,
	"document_status" text DEFAULT 'PENDING',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "booking_orders_booking_sn_unique" UNIQUE("booking_sn"),
	CONSTRAINT "booking_orders_shop_id_booking_sn_key" UNIQUE("shop_id","booking_sn")
);
--> statement-breakpoint
CREATE TABLE "hpp_master" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hpp_master_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"item_sku" text NOT NULL,
	"tier1_variation" text NOT NULL,
	"cost_price" numeric,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"canonical_sku" text,
	CONSTRAINT "hpp_master_user_sku_tier1_unique" UNIQUE("user_id","item_sku","tier1_variation")
);
--> statement-breakpoint
CREATE TABLE "item_models" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "item_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_id" bigint NOT NULL,
	"model_id" bigint NOT NULL,
	"model_name" text NOT NULL,
	"current_price" numeric NOT NULL,
	"original_price" numeric NOT NULL,
	"stock_info" jsonb NOT NULL,
	"model_status" text NOT NULL,
	CONSTRAINT "unique_item_model" UNIQUE("item_id","model_id")
);
--> statement-breakpoint
CREATE TABLE "item_variations" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "item_variations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_id" bigint NOT NULL,
	"variation_id" bigint NOT NULL,
	"variation_name" text NOT NULL,
	"variation_option" jsonb NOT NULL,
	CONSTRAINT "unique_item_variation" UNIQUE("item_id","variation_id")
);
--> statement-breakpoint
CREATE TABLE "items" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_id" bigint NOT NULL,
	"shop_id" bigint NOT NULL,
	"category_id" bigint NOT NULL,
	"item_name" text NOT NULL,
	"description" text NOT NULL,
	"item_sku" text NOT NULL,
	"create_time" bigint NOT NULL,
	"update_time" bigint NOT NULL,
	"weight" numeric,
	"image" jsonb,
	"logistic_info" jsonb,
	"pre_order" jsonb,
	"condition" text NOT NULL,
	"item_status" text NOT NULL,
	"has_model" boolean DEFAULT false NOT NULL,
	"brand" jsonb,
	"item_dangerous" integer DEFAULT 0 NOT NULL,
	"description_type" text NOT NULL,
	"size_chart_id" bigint,
	"promotion_image" jsonb,
	"deboost" boolean DEFAULT false NOT NULL,
	"authorised_brand_id" bigint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "items_item_id_unique" UNIQUE("item_id")
);
--> statement-breakpoint
CREATE TABLE "keluhan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "keluhan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_pengguna" varchar NOT NULL,
	"nama_toko" varchar NOT NULL,
	"jenis_keluhan" text NOT NULL,
	"nomor_invoice" varchar NOT NULL,
	"create_at" timestamp with time zone DEFAULT now(),
	"status_keluhan" varchar DEFAULT 'BELUM DITANGANI',
	"deskripsi_keluhan" text,
	"status_pesanan" text,
	"shop_id" text,
	"msg_id" text,
	"userid" bigint,
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'),
	CONSTRAINT "keluhan_nomor_invoice_unique" UNIQUE("nomor_invoice")
);
--> statement-breakpoint
CREATE TABLE "logistic" (
	"order_sn" varchar NOT NULL,
	"package_number" varchar NOT NULL,
	"logistics_status" varchar,
	"shipping_carrier" varchar,
	"parcel_chargeable_weight_gram" integer,
	"recipient_name" varchar,
	"recipient_phone" varchar,
	"recipient_town" varchar,
	"recipient_district" varchar,
	"recipient_city" varchar,
	"recipient_state" varchar,
	"recipient_region" varchar,
	"recipient_zipcode" varchar,
	"recipient_full_address" text,
	"tracking_number" text,
	CONSTRAINT "logistic_order_sn_package_number_pk" PRIMARY KEY("order_sn","package_number")
);
--> statement-breakpoint
CREATE TABLE "openai_api" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "openai_api_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"api_key" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "order_escrow" (
	"order_sn" varchar PRIMARY KEY NOT NULL,
	"shop_id" bigint NOT NULL,
	"escrow_amount" numeric,
	"buyer_total_amount" numeric,
	"original_price" numeric,
	"seller_discount" numeric,
	"shopee_discount" numeric,
	"voucher_from_seller" numeric,
	"commission_fee" numeric,
	"service_fee" numeric,
	"seller_transaction_fee" numeric,
	"actual_shipping_fee" numeric,
	"buyer_payment_method" varchar,
	"updated_at" timestamp with time zone DEFAULT now(),
	"escrow_amount_after_adjustment" numeric DEFAULT '0',
	"ams_commission_fee" numeric,
	CONSTRAINT "unique_order_shop" UNIQUE("order_sn","shop_id")
);
--> statement-breakpoint
CREATE TABLE "order_items" (
	"order_sn" varchar NOT NULL,
	"item_id" bigint,
	"model_id" bigint NOT NULL,
	"order_item_id" bigint NOT NULL,
	"item_name" varchar,
	"item_sku" varchar,
	"model_name" varchar,
	"model_sku" varchar,
	"model_quantity_purchased" integer,
	"model_original_price" numeric,
	"model_discounted_price" numeric,
	"wholesale" boolean,
	"weight" numeric,
	"add_on_deal" boolean,
	"main_item" boolean,
	"add_on_deal_id" bigint,
	"promotion_type" varchar,
	"promotion_id" bigint,
	"promotion_group_id" bigint,
	"image_url" text,
	CONSTRAINT "order_items_order_sn_order_item_id_model_id_pk" PRIMARY KEY("order_sn","order_item_id","model_id")
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"order_sn" varchar PRIMARY KEY NOT NULL,
	"buyer_user_id" bigint,
	"buyer_username" varchar,
	"create_time" bigint,
	"order_status" varchar,
	"currency" varchar,
	"total_amount" numeric,
	"shipping_carrier" varchar,
	"estimated_shipping_fee" numeric,
	"actual_shipping_fee_confirmed" boolean,
	"cod" boolean,
	"days_to_ship" integer,
	"ship_by_date" bigint,
	"payment_method" varchar,
	"fulfillment_flag" varchar,
	"message_to_seller" text,
	"note" text,
	"note_update_time" bigint,
	"order_chargeable_weight_gram" integer,
	"pickup_done_time" bigint,
	"update_time" bigint,
	"shop_id" bigint NOT NULL,
	"pay_time" bigint,
	"cancel_by" text,
	"cancel_reason" text,
	"escrow_amount_after_adjustment" numeric DEFAULT '0',
	"tracking_number" text,
	"is_printed" boolean DEFAULT false,
	"document_status" text DEFAULT 'PENDING'
);
--> statement-breakpoint
CREATE TABLE "pengaturan" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "pengaturan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"openai_api" text,
	"openai_model" text,
	"openai_temperature" numeric,
	"openai_prompt" text,
	"auto_ship_interval" integer DEFAULT 5 NOT NULL,
	"in_cancel_msg" text,
	"in_return_msg" text,
	"in_return_status" boolean DEFAULT true,
	"in_cancel_status" boolean DEFAULT true,
	CONSTRAINT "pengaturan_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "perubahan_pesanan" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "perubahan_pesanan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_pengguna" varchar NOT NULL,
	"nama_toko" varchar NOT NULL,
	"nomor_invoice" varchar,
	"perubahan" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"status" text DEFAULT 'BARU' NOT NULL,
	"status_pesanan" text,
	"detail_perubahan" text,
	"shop_id" text,
	"msg_id" text,
	"userid" bigint NOT NULL,
	CONSTRAINT "perubahan_pesanan_nomor_invoice_unique" UNIQUE("nomor_invoice")
);
--> statement-breakpoint
CREATE TABLE "shopee_notifications" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "shopee_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"notification_type" varchar NOT NULL,
	"shop_id" bigint,
	"data" jsonb NOT NULL,
	"processed" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"read" boolean DEFAULT false NOT NULL,
	"shop_name" text
);
--> statement-breakpoint
CREATE TABLE "shopee_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shopee_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"shop_id" bigint NOT NULL,
	"shop_name" text NOT NULL,
	"partner_id" bigint NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"access_token_expiry" timestamp with time zone NOT NULL,
	"refresh_token_expiry" timestamp with time zone NOT NULL,
	"authorization_expiry" timestamp with time zone NOT NULL,
	"last_refresh_attempt" timestamp with time zone,
	"refresh_count" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid,
	CONSTRAINT "shopee_tokens_shop_id_unique" UNIQUE("shop_id")
);
--> statement-breakpoint
CREATE TABLE "sku_cost_margins" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sku_cost_margins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"item_sku" text NOT NULL,
	"cost_price" numeric,
	"margin_percentage" numeric,
	"is_using_cost" boolean DEFAULT false NOT NULL,
	"last_updated_by" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid,
	CONSTRAINT "sku_cost_margins_item_sku_user_id_key" UNIQUE("item_sku","user_id")
);
--> statement-breakpoint
CREATE TABLE "subscription_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"price" numeric NOT NULL,
	"max_shops" integer NOT NULL,
	"features" jsonb,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "subscription_plans_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "user_subscriptions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"plan_id" uuid NOT NULL,
	"status" text NOT NULL,
	"start_date" timestamp with time zone DEFAULT now(),
	"end_date" timestamp with time zone,
	"payment_status" text,
	"payment_reference" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "auto_ship_chat" ADD CONSTRAINT "auto_ship_chat_shop_id_shopee_tokens_shop_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shopee_tokens"("shop_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "item_models" ADD CONSTRAINT "item_models_item_id_items_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("item_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "item_variations" ADD CONSTRAINT "item_variations_item_id_items_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("item_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "logistic" ADD CONSTRAINT "logistic_order_sn_orders_order_sn_fk" FOREIGN KEY ("order_sn") REFERENCES "public"."orders"("order_sn") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_escrow" ADD CONSTRAINT "order_escrow_order_sn_orders_order_sn_fk" FOREIGN KEY ("order_sn") REFERENCES "public"."orders"("order_sn") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_escrow" ADD CONSTRAINT "order_escrow_shop_id_shopee_tokens_shop_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shopee_tokens"("shop_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_sn_orders_order_sn_fk" FOREIGN KEY ("order_sn") REFERENCES "public"."orders"("order_sn") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_shop_id_shopee_tokens_shop_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shopee_tokens"("shop_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_subscriptions" ADD CONSTRAINT "user_subscriptions_plan_id_subscription_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."subscription_plans"("id") ON DELETE no action ON UPDATE no action;