-- Custom indexes not auto-generated by Drizzle schema
-- Run after initial migration

-- ══ orders ══
CREATE INDEX IF NOT EXISTS idx_orders_create_time ON orders USING btree (create_time);
CREATE INDEX IF NOT EXISTS idx_orders_create_time_shop_id ON orders USING btree (create_time, shop_id);
CREATE INDEX IF NOT EXISTS idx_orders_pay_time ON orders USING btree (pay_time);
CREATE INDEX IF NOT EXISTS idx_orders_shop_id ON orders USING btree (shop_id);

-- ══ order_escrow ══
CREATE INDEX IF NOT EXISTS idx_order_escrow_order_sn ON order_escrow USING btree (order_sn);
CREATE INDEX IF NOT EXISTS idx_order_escrow_shop_id ON order_escrow USING btree (shop_id);

-- ══ shopee_tokens ══
CREATE INDEX IF NOT EXISTS idx_is_active ON shopee_tokens USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_shop_id ON shopee_tokens USING btree (shop_id);
CREATE INDEX IF NOT EXISTS idx_shop_name ON shopee_tokens USING btree (shop_name);

-- ══ booking_orders ══
CREATE INDEX IF NOT EXISTS idx_booking_orders_booking_sn ON booking_orders USING btree (booking_sn);
CREATE INDEX IF NOT EXISTS idx_booking_orders_booking_status ON booking_orders USING btree (booking_status) WHERE booking_status IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_orders_create_time ON booking_orders USING btree (create_time) WHERE create_time IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_orders_document_status ON booking_orders USING btree (document_status) WHERE document_status IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_orders_is_printed ON booking_orders USING btree (is_printed);
CREATE INDEX IF NOT EXISTS idx_booking_orders_item_list_gin ON booking_orders USING gin (item_list);
CREATE INDEX IF NOT EXISTS idx_booking_orders_order_sn ON booking_orders USING btree (order_sn) WHERE order_sn IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_orders_recipient_address_gin ON booking_orders USING gin (recipient_address);
CREATE INDEX IF NOT EXISTS idx_booking_orders_shop_id ON booking_orders USING btree (shop_id);
CREATE INDEX IF NOT EXISTS idx_booking_orders_tracking_number ON booking_orders USING btree (tracking_number) WHERE tracking_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_orders_update_time ON booking_orders USING btree (update_time) WHERE update_time IS NOT NULL;

-- ══ shopee_notifications ══
CREATE INDEX IF NOT EXISTS idn_notification_type ON shopee_notifications USING btree (notification_type);
CREATE INDEX IF NOT EXISTS idn_shop_id ON shopee_notifications USING btree (shop_id);

-- ══ item_variations ══
CREATE INDEX IF NOT EXISTS idx_item_variations_item_id ON item_variations USING btree (item_id);

-- ══ sku_cost_margins ══
CREATE INDEX IF NOT EXISTS idx_sku_cost_margins_sku ON sku_cost_margins USING btree (item_sku);
CREATE INDEX IF NOT EXISTS idx_sku_cost_margins_user_id ON sku_cost_margins USING btree (user_id);

-- ══ hpp_master ══
CREATE INDEX IF NOT EXISTS idx_hpp_master_user_id ON hpp_master USING btree (user_id);
